Revert "podcata-data: Let r2d2 use the default number of connections"
This reverts commit b91289dfb535b85d2cf2878089b906fae6f4681a

After this we somehow keep ending up with a locked database and it needs
to be looked at.

```
thread 'tokio-runtime-worker' (202) panicked at podcasts-gtk/src/download_covers.rs:446:82:
called `Result::unwrap()` on an `Err` value: DieselResultError(DatabaseError(Unknown, "database is locked"))
```